---
title: "Visualizing the Pangolin Products Trade"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualizing the Pangolin Products Trade}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>"
)
```
  
```{r setup}
library(citesdb)
library(tidyverse)
library(CoordinateCleaner)
library(ggplot2)
library(gganimate)
library(sf)
library(rnaturalearth)
library(png)
library(grid)
```

```{r}
pangolin_shipments <- cites_shipments() %>%
  filter(Order == "Pholidota", Purpose %in% c(NA_character_, "T")) %>%
  select(-Purpose, -Import.permit.RandomID, -Export.permit.RandomID, -Origin.permit.RandomID, -Class, -Order, -Family, -Genus) %>% 
  collect()
cites_disconnect()
```
```{r}
cref <- CoordinateCleaner::countryref %>% 
  filter(type == "country") %>% 
  distinct(iso2, .keep_all = TRUE) %>% 
  select(iso2, centroid.lon, centroid.lat)

pangolin_shipments <- pangolin_shipments %>% 
  mutate(start = coalesce(Origin, Exporter)) %>% 
  left_join(cref, by = c("start" = "iso2")) %>% 
  rename(start.lon = centroid.lon, start.lat = centroid.lat) %>% 
  left_join(cref, by = c("Importer" = "iso2")) %>% 
  rename(end.lon = centroid.lon, end.lat = centroid.lat) %>% 
  filter(Importer != start) %>% 
  filter(!is.na(start.lon), !is.na(end.lon), !is.na(start.lat), !is.na(end.lat)) %>% 
  mutate(id = seq_len(n()))
```

http://www.minchunzhou.com/travelhistory.html
https://weiminwang.blog/2015/06/24/use-r-to-plot-flight-routes-on-a-fancy-world-background/
https://stackoverflow.com/questions/52510967/create-a-flyover-map-animation-using-ggmap-and-gganimate



```{r}
pg <- pangolin_shipments %>% 
  gather("type", "coord", start.lat, start.lon, end.lat, end.lon) %>% 
  separate(type, into =  c("type", "axis")) %>% 
  spread(axis, coord) %>% 
  arrange(id, Year) %>% 
  group_by(Year) %>% 
  mutate(time = seq(0, 1, length.out = n() + 1)[-1]) %>% 
  ungroup() %>% 
  mutate(time = min(Year) + time)

pt <- pg %>% 
  st_as_sf(coords = c("lon", "lat")) %>% 
  sf::st_set_crs(4326) %>% 
  st_transform(crs = "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") %>% 
  as_tibble() %>% 
  mutate(x = st_coordinates(geometry)[,1], y = st_coordinates(geometry)[,2])


countries <- ne_countries(returnclass = "sf") %>% 
  filter(name != "Antarctica") %>% 
  st_transform(crs = "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") %>% 
  st_geometry()

left_join(countries, cites_parties(), by = "")
```

```{r}
img <- readPNG(here::here("vignettes", "EHA_Logo_369C.png"))
g <- rasterGrob(img, interpolate = FALSE)

gga <- ggplot(data = pt) +
  geom_sf(data = countries, color = "#FFFFFF", fill = NA) +
  geom_point(data = filter(pt, Year <= 1982), aes(x = x, y = y, group = id, col = Term), size = 2, inherit.aes = FALSE) +
  scale_x_continuous(limits = c(-14000000, 18000000), expand = c(0,0)) +
  scale_y_continuous(limits = c(-8500000, 9200000), expand = c(0,0)) +
  coord_cartesian(clip = 'off') +
  annotation_custom(g, xmin = 8500000, xmax = 17500000, ymin = -8300000 , ymax = -5310000) +
  shadow_wake(wake_length = 0.1, falloff = "linear", size = NULL) +
  transition_time(time) +
  #  labs(title = "Year") +
  labs(subtitle = "Year: {round(frame_time, 0)}") +
  theme(
    text = element_text(color = "#FFFFFF", family = "Avenir"),
    title = element_text(size = 28),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_line(color = "#00505C"),
    panel.background = element_rect(fill = "#00505C", color = "#00505C"),
    plot.background = element_rect(fill = "#00505C", color = "#00505C"),
    legend.position = "none", #c(0.85, 0.85),
    legend.background = element_rect(fill = "#00505C", color = "#00505C"),
    plot.margin = margin(t = 0.5, r = 0.2, b = 0.2, l = 0, unit = "in"),
)


png("static.png", width = 1280, height = 720, bg = "#00505C")
plot(gga)
dev.off()

anim <- gga %>% animate(detail = 1, type = "cairo", fps = 10, duration = 10, renderer = av_renderer("pangolin_trade.mp4"), width = 1280, height = 720)

```

